name: Waka Readme

env:
  TZ: Asia/Shanghai

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    - cron: "3 44 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
